package GUI;

import Domain.FileManagement;
import Domain.Person;
import Domain.PersonRegistration;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author reych
 */
public class idTittle extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    public idTittle() {
        initComponents();
        setVisibleFalse();
        setInstances();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        JTextField = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        idTittle = new javax.swing.JLabel();
        nameTittle = new javax.swing.JLabel();
        lastNameTittle = new javax.swing.JLabel();
        phoneTittle = new javax.swing.JLabel();
        civilStateTittle = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        civilStateInput = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        searchTittle = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        FindDataInput = new javax.swing.JTextField();
        peopleComboBox = new javax.swing.JComboBox<>();
        dataTittle = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        JTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        JTextField.setText("NAME");
        JTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jTextField6.setText("Phone");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        x.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration");
        setBackground(new java.awt.Color(0, 51, 153));
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(6, 6));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        idTittle.setText("Id:");
        jPanel1.add(idTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 158, -1, -1));

        nameTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        nameTittle.setText("Name:");
        jPanel1.add(nameTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 204, -1, -1));

        lastNameTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        lastNameTittle.setText("Last name:");
        jPanel1.add(lastNameTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 246, -1, -1));

        phoneTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        phoneTittle.setText("PHONE:");
        jPanel1.add(phoneTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 296, -1, -1));

        civilStateTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        civilStateTittle.setText("CIVIL STATE:");
        jPanel1.add(civilStateTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 342, -1, -1));

        idInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        idInput.setText("ID");
        idInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 154, 132, -1));

        nameInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        nameInput.setText("Name");
        nameInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 246, 132, -1));

        lastNameInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lastNameInput.setText("Last name");
        lastNameInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 200, 132, -1));

        phoneInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        phoneInput.setText("Phone");
        phoneInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(phoneInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 292, 132, -1));

        civilStateInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        civilStateInput.setText("Civil state");
        civilStateInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(civilStateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 338, 132, -1));

        registerBtn.setBackground(new java.awt.Color(0, 0, 102));
        registerBtn.setFont(new java.awt.Font("Castellar", 1, 16)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationMouseClicked(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 384, -1, -1));

        searchTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        searchTittle.setText("Search:");
        jPanel1.add(searchTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 23, -1, -1));

        searchBtn.setBackground(new java.awt.Color(0, 0, 102));
        searchBtn.setFont(new java.awt.Font("Castellar", 1, 16)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 20, 112, -1));

        FindDataInput.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        FindDataInput.setText("Data");
        FindDataInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        FindDataInput.setMinimumSize(new java.awt.Dimension(3, 28));
        FindDataInput.setPreferredSize(new java.awt.Dimension(37, 28));
        jPanel1.add(FindDataInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 19, 239, -1));

        peopleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty" }));
        peopleComboBox.setSelectedItem(people);
        peopleComboBox.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel1.add(peopleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 95, 313, -1));

        dataTittle.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        dataTittle.setText("Data:");
        jPanel1.add(dataTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, -1, -1));

        alert.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        alert.setForeground(new java.awt.Color(153, 0, 0));
        alert.setText("alert");
        jPanel1.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 428, 196, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 510));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(312, 30));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(312, 30));
        jMenuBar1.setOpaque(true);
        jMenuBar1.setVerifyInputWhenFocusTarget(false);

        jMenu2.setText("Search");
        jMenu2.setActionCommand("SearchOption");
        jMenu2.setFocusCycleRoot(true);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchOptionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Registration");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationOptionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setVisibleFalse() {
        this.registerBtn.setVisible(false);
        this.searchBtn.setVisible(false);
        this.idTittle.setVisible(false);
        this.nameTittle.setVisible(false);
        this.lastNameTittle.setVisible(false);
        this.phoneTittle.setVisible(false);
        this.civilStateTittle.setVisible(false);
        this.searchTittle.setVisible(false);
        this.dataTittle.setVisible(false);
        this.idInput.setVisible(false);
        this.nameInput.setVisible(false);
        this.lastNameInput.setVisible(false);
        this.phoneInput.setVisible(false);
        this.civilStateInput.setVisible(false);
        this.FindDataInput.setVisible(false);
        this.peopleComboBox.setVisible(false);
        this.alert.setText("");

    }

    private void setInstances() {
        fileManagement = FileManagement.getInstance();
        fileManagement.actualizaLista();
        people = fileManagement.getPeople();
        registration = new PersonRegistration();
    }

    private void JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldActionPerformed
    }//GEN-LAST:event_JTextFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void searchOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOptionMouseClicked
        setVisibleSearchOption();
    }//GEN-LAST:event_searchOptionMouseClicked

    private void RegistrationOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationOptionMouseClicked
        setVisibleFalse();
        setVisibleRegisterOption();

    }//GEN-LAST:event_RegistrationOptionMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        showPeopleData(this.FindDataInput.getText());
    }//GEN-LAST:event_searchBtnActionPerformed

    private void RegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationMouseClicked
        registration();
    }//GEN-LAST:event_RegistrationMouseClicked

    private void registration() {
        if (!idInput.getText().isEmpty() & !nameInput.getText().isEmpty()
                & !lastNameInput.getText().isEmpty() & !phoneInput.getText().isEmpty()
                & !civilStateInput.getText().isEmpty()) {
            this.alert.setVisible(true);

            person = registration.insertPersona(idInput.getText(), nameInput.getText(),
                    lastNameInput.getText(), phoneInput.getText(), civilStateInput.getText());
            if (person != null) {
                if (!fileManagement.verifyExistence(person.getId())) {
                    try {
                        this.fileManagement.savePerson(person);
                        // successful
                            alert.setText("Successful proccess");
                    } catch (IOException | ClassNotFoundException ex) {
                        //error
                            alert.setText("Internal error");
                    }       
                } else {
                    //usuario existe
                   alert.setText("Registered user");
                }
            }

        } else {
            //incompleto
            alert.setText("Incomplete data");
        }
    }

    private void showPeopleData(String find) {
        setInstances();
        peopleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 0; i < people.size(); i++) {            
            if (people.get(i).completeData().toLowerCase().contains(find.toLowerCase())) {
                this.peopleComboBox.addItem(people.get(i).toString());
            }
        }

    }

    private void setVisibleSearchOption() {
        this.setVisibleFalse();
        this.searchBtn.setVisible(true);
        this.searchTittle.setVisible(true);
        this.dataTittle.setVisible(true);
        this.FindDataInput.setVisible(true);
        this.peopleComboBox.setVisible(true);
    }

    private void setVisibleRegisterOption() {
        this.registerBtn.setVisible(true);
        this.idTittle.setVisible(true);
        this.nameTittle.setVisible(true);
        this.lastNameTittle.setVisible(true);
        this.phoneTittle.setVisible(true);
        this.civilStateTittle.setVisible(true);
        this.idInput.setVisible(true);
        this.nameInput.setVisible(true);
        this.lastNameInput.setVisible(true);
        this.phoneInput.setVisible(true);
        this.civilStateInput.setVisible(true);
        this.dataTittle.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* try {
            //instancias
            PersonRegistration r=new PersonRegistration();
            Person p =r.insertPersona();
            FileManagement mA=Domain.FileManagement.getInstance();
            
            //manejo de datos para registro por medio de JOptionPane
            if (p!=null && mA.verifyExistence(p.getId())==false) {
               mA.savePerson(p);
            }else if(p==null){
            JOptionPane.showMessageDialog(null, "Datos incompletos.", "Error de registro", 0);
            }else if(p!=null && mA.verifyExistence(p.getId())==true){
             JOptionPane.showMessageDialog(null, "Usuario ingresado previamente.", "Error de registro", 0);
            }
            
            mA.actualizaLista();
            if (!mA.archivoCompleto().isEmpty()) {
                JOptionPane.showMessageDialog(null,  mA.archivoCompleto());
            }

        } catch (IOException | ClassNotFoundException ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());

        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(idTittle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new idTittle().setVisible(true);
            }
        });
    }

    //Variables internas
    private PersonRegistration registration;
    private FileManagement fileManagement;
    private Person person;
    private ArrayList<Person> people;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FindDataInput;
    private javax.swing.JTextField JTextField;
    private javax.swing.JLabel alert;
    private javax.swing.JTextField civilStateInput;
    private javax.swing.JLabel civilStateTittle;
    private javax.swing.JLabel dataTittle;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idTittle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameTittle;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameTittle;
    private javax.swing.JComboBox<String> peopleComboBox;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneTittle;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchTittle;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

}